name: lint

on:
    push:
        branches:
            - react

jobs:
    eslint:
        runs-on: node:14.17.0-alpine
        steps:
            - name: Checkout
              uses: action/checkout@v2
              with:
                  ref: react
            - name: Install devendencies
              run: npm install
            - name: Lint source code with ESLint
              run: npm run lint
