name: lint

on:
    push:
        branches:
            - react

jobs:
    eslint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 14.x ]
        steps:
            -   name: Checkout
                uses: action/checkout@v2
                with:
                    ref: react
            -   name: Use Node.js ${{ matrix.node-version }}
                    uses: actions/setup-node@v2
                    with:
                        node-version: ${{ matrix.node-version }}
                        cache: 'npm'
                        -   name: Install devendencies
            run: npm install
            -   name: Lint source code with ESLint
                run: npm run lint
